title: Despliegue App GO
description: Ejemplo despliegue App
informationalText: Ejemplo terraform + Ansible
schemaVersion: 1.1.0
version: "20190304"
#version: "202008"
groupings:
  - title: "Ambiente"
    variables:
      - ${apodo}
      - ${region}
      - ${compartment_ocid}
      - ${adomain}
  - title: "Redes"
    variables:
      - ${comparedes}
      - ${vcn}
      - ${reddmz}
      - ${redapp}
      - ${reddata}
      - ${nsg}
  - title: "App"
    variables:
      - ${cantidad}
      - ${shape}
      - ${ocpu}
      - ${memoria}
      - ${password}
      - ${ssh_public_key}

variables:
  apodo:
    type: string
    minLength: 1
    maxLength: 8
    pattern: "[a-zA-Z0-9]"
    default: "dev"
    title: Nombre Ambiente
    required: true

  region:
    type: oci:identity:region:name
    title: Region
    description: Region a Usar
    required: true

  compartment_ocid:
    type: oci:identity:compartment:id
    title: Compartment para Ambiente
    description: Compartment para Ambiente
    required: true

  adomain:
    type: oci:identity:availabilitydomain:name
    title: Availability Domain
    description: donde queda
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}

  cantidad:
    title: Cantidad de App Servers
    visible: true
    type: integer
    default: 1
    minimum: 1
    maximum: 8
    required: true

  shape:
    type: oci:core:instanceshape:name
    required: true
    title: Shape
    description: Imagen
    dependsOn:
      compartmentId: ${compartment_ocid}
#      region: ${region}
#      availabilityDomain: ${adomain}
#      imageId: ${imagen}

  ocpu:
    title: Cantidad de OCPU (Aplica en shapes Flex)
    type: integer
    default: 1
    minimum: 1
    maximum: 24
    required: false

  memoria:
    type: number
    title: Cantidad de Memoria en GB (Aplica en shapes Flex)
    default: 15
    required: false

  password:
    title: Password Database
    visible: true
    type: password
    required: true

  ssh_public_key:
    type: oci:core:ssh:publickey
    title: Llave de acceso ssh Publica
    description: Llave Pública de Acceso SSH
    required: true

  comparedes:
    type: oci:identity:compartment:id
    title: Compartment donde estan creadas las redes
    description: Compartment donde estan creadas las redes
    required: true

  vcn:
    type: oci:core:vcn:id
    dependsOn:
      compartmentId: ${comparedes}
    required: true
    title: VCN
    description: Seleccionar VCN

  reddmz:
    type: oci:core:subnet:id
    required: true
    title: Red DMZ
    description: Red para LB
    dependsOn:
      vcnId: ${vcn}
      compartmentId: ${comparedes}

  redapp:
    type: oci:core:subnet:id
    required: true
    title: Red APP
    description: Red para Maquina
    dependsOn:
      vcnId: ${vcn}
      compartmentId: ${comparedes}

  reddata:
    type: oci:core:subnet:id
    required: true
    title: Red DATOS
    description: Red para Maquina
    dependsOn:
      vcnId: ${vcn}
      compartmentId: ${comparedes}

  nsg:
    type: oci:core:nsg:id
    required: true
    title: NSG autonomous
    description: NSG asignada a BD
    dependsOn:
      vcnId: ${vcn}
      compartmentId: ${comparedes}
